### ISSUE TITLE
Remove sharp module

### ISSUE THREAD

**Issue by HubertBalcerzak** [Starchasers/up#109]
Sharp module regurally causes build failures in CI build and in local dev environments. It must be replaced by some alternative.

**Comment by Kuboczoch** [comment]
First of all: we can't do that, because it is an essential plugin.

I searched it and I found that it is crashing on some versions of node make sure to have the correct one. For example, I have just downloaded it on my laptop and it is working correctly with npm install and gatsby build. I'm using node `v12.16.1`

**Comment by Kuboczoch** [comment]
I have been searching for the solution and everyone is just deleting all `node_modules` and starting again. Make sure to not have any broken library in the npm cache folder. Probably there is a package in the dependencies of the sharp module that is causing this but the simplest workaround is to remove and install it again.

@HubertBalcerzak please add `rm -rf ./node_modules && npm install` to the gatsby build in some try-catch.

**Comment by HubertBalcerzak** [comment]
should be fixed by #133
